import React, { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { clashDisplay, outfit } from "@/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html
      lang="en"
      className={`${clashDisplay.variable} ${outfit.variable} font-outfit`}
    >
      <body>{children}</body>
      <Analytics />
    </html>
  );
}
