import { PropsWithChildren } from "react";
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { clashDisplay, outfit } from "@/fonts";
import { NoiseBackground } from "@/shared/components/NoiseBackground";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html
      className={`${clashDisplay.variable} ${outfit.variable} font-outfit`}
      lang="en"
    >
      <body className="bg-black">
        <NoiseBackground />
        {children}
        <SpeedInsights />
      </body>
      <Analytics />
    </html>
  );
}
